### ISSUE TITLE
What sort of wizard are you?

### ISSUE THREAD

**Issue by xk** [stecker870/MacBook-Pro-15-Zoll-late-2011-Graphics-Card-Fix-#6]
Hi,

I just want to say **THANK YOU**, but please, pray tell what sort of genius are you to know what to touch in the .kext to make it work? ( it's a rhetorical question :-) )

What I did: Boot from the Recovery HD, open the terminal and type csrutil disable, remove the old .kext, copy this one to /Extensions, reboot and check if it works, reboot again in recovery mode, re-enable again with csrutil enable, et voilà, [x] DONE, **PERFECT** !

Macbook8,3 17" late 2011, i7@2.4

Thank you very much my friend.

**Comment by stecker870** [comment]
Hey!
First things first, your welcome ! :) i am glad that it worked for you...
Well long time ago I ran like almost everybody with that MBP late 2011 model into that  dGPU issue! xD
Ahmmm Long story short... had to experiment a round and needed to read around the hole internet until I figured it out and got it to work :)

**Comment by xk** [comment]
Hi!

You saved my life, or rather, my MBP´s I should say, hahaha.

Cheers,
Have a nice day,
Jorge.
